### ISSUE TITLE
Improve query parsing and validation

### ISSUE THREAD

**Issue by Maximilien-R** [tartiflette/tartiflette#121]
It might be interesting to change the way queries are parsed and validated.

Currently we use the `libgraphqlparser` to browse the nodes of the query using callback functions that are called each time the parser encounters a new node in the document. At each node encountered the callback function generates a `VisitorElement` object which is then passed when calling the `update` method of the `Visitor` instance which is responsible of business logic (validation, addition of information to the visitor context, creation of `Node` object...).

These different processes are complex and long to execute. The addition of the management of new errors gradually make the code less and less readable and more difficult to maintain.

To tackle this problem, we could dissociate this unique treatment into separate steps:
1. Parse the query to generate a `DocumentNode` object containing all the information related to the query.
This step can be easily done by calling the `graphql_ast_to_json` `libgraphqlparser` function which analyzes the query and returns a string in `JSON` format containing all the information related to the query. This string could then be computed into a `DocumentNode` object.
2. Apply the set of validation rules defined by the GraphQL specification to this `DocumentNode` object.

Proceed in this way to several advantages:
1. Allow to cache for each query the generation of the `DocumentNode` and the application of validation rules.
2. Delete a lot of code (`Visitor`,` VisitorContext` & most of the code contained in `cffi` parser) and gain in simplicity/readability/maintainability.
3. Have a `DocumentNode` object conforming to the `GraphQL` [language specifications](https://facebook.github.io/graphql/June2018/#sec-Language). This would allow to be more faithful to the specifications but also to facilitate the on-boarding of new collaborators.
4. Be closer to the specification and allow to deal with some particular case still poorly managed currently (such as the merge of `SelectionSet`).

# TODO
- [x] Implements functions which parse a SDL or query string to a `DocumentNode` instance
- [x] Cache SDL/query parsing & validation
- [x] Use `DocumentNode` to build schema
- [x] Use `DocumentNode` to execute query

**Comment by abusi** [comment]
:+1:
